---
- name: Setup the homeserver
  hosts: all
  become: true

  tasks:
    - name: Update server and install essential packages
      ansible.builtin.include_tasks: tasks/essential.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: Deploy docker apps
      ansible.builtin.include_tasks: "tasks/{{ item }}.yml"
      loop:
        - traefik
        - code_server
        - filebrowser
        - monitoring
        - n8n
        - portainer
        - prowlarr
        - qbittorrent
        - radarr
        - requestrr
        - sonarr
        - plex
        - uptime_kuma
        - watchtower
        - wireguard

    - name: Modify ownership of data and docker_apps directories
      ansible.builtin.include_tasks: tasks/add_ownership.yml

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting server to finish setup"

    - name: Restart traefik container to ensure it can find authelia middleware
      community.docker.docker_container:
        name: traefik
        state: started
        restart: true
      when: traefik_authelia_check.status != 200
